"""initial schema

Revision ID: a379d9d5ed0b
Revises: 
Create Date: 2026-03-08 10:36:33.198592
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a379d9d5ed0b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ecosystems',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uaf_agreement_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('agreements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ecosystem_id', sa.Uuid(), nullable=False),
    sa.Column('agreement_id', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('proposer', sa.String(length=255), nullable=True),
    sa.Column('affected_parties', sa.JSON(), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('hierarchy_level', sa.String(length=50), nullable=False),
    sa.Column('parent_agreement_id', sa.Uuid(), nullable=True),
    sa.Column('review_date', sa.Date(), nullable=True),
    sa.Column('sunset_date', sa.Date(), nullable=True),
    sa.Column('ratification_date', sa.Date(), nullable=True),
    sa.Column('created_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ecosystem_id'], ['ecosystems.id'], ),
    sa.ForeignKeyConstraint(['parent_agreement_id'], ['agreements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agreements_ecosystem_id', 'agreements', ['ecosystem_id'], unique=False)
    op.create_table('decision_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ecosystem_id', sa.Uuid(), nullable=False),
    sa.Column('record_id', sa.String(length=100), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('holding', sa.Text(), nullable=True),
    sa.Column('ratio_decidendi', sa.Text(), nullable=True),
    sa.Column('obiter_dicta', sa.Text(), nullable=True),
    sa.Column('deliberation_summary', sa.Text(), nullable=True),
    sa.Column('source_skill', sa.String(length=100), nullable=True),
    sa.Column('source_layer', sa.Integer(), nullable=True),
    sa.Column('artifact_type', sa.String(length=50), nullable=True),
    sa.Column('artifact_reference', sa.String(length=255), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('precedent_level', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('overruled_by', sa.String(length=100), nullable=True),
    sa.Column('superseded_by', sa.String(length=100), nullable=True),
    sa.Column('related_records', sa.JSON(), nullable=True),
    sa.Column('review_date', sa.Date(), nullable=True),
    sa.Column('recorder', sa.String(length=255), nullable=True),
    sa.Column('recorder_role', sa.String(length=100), nullable=True),
    sa.Column('verification_by', sa.String(length=255), nullable=True),
    sa.Column('verification_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ecosystem_id'], ['ecosystems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_decision_records_ecosystem_id', 'decision_records', ['ecosystem_id'], unique=False)
    op.create_table('members',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ecosystem_id', sa.Uuid(), nullable=False),
    sa.Column('member_id', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('current_status', sa.String(length=50), nullable=False),
    sa.Column('profile', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('profile_picture', sa.String(length=500), nullable=True),
    sa.Column('skills_offered', sa.JSON(), nullable=True),
    sa.Column('skills_needed', sa.JSON(), nullable=True),
    sa.Column('onboarding_status', sa.String(length=50), nullable=True),
    sa.Column('kyc_status', sa.String(length=50), nullable=True),
    sa.Column('last_governance_activity_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ecosystem_id'], ['ecosystems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_members_ecosystem_id', 'members', ['ecosystem_id'], unique=False)
    op.create_table('proposals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ecosystem_id', sa.Uuid(), nullable=False),
    sa.Column('proposal_id', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('decision_type', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('proposer', sa.String(length=255), nullable=True),
    sa.Column('co_sponsors', sa.JSON(), nullable=True),
    sa.Column('affected_domain', sa.String(length=255), nullable=True),
    sa.Column('impacted_parties', sa.JSON(), nullable=True),
    sa.Column('urgency', sa.String(length=50), nullable=True),
    sa.Column('proposed_change', sa.Text(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('created_date', sa.Date(), nullable=True),
    sa.Column('advice_deadline', sa.Date(), nullable=True),
    sa.Column('consent_deadline', sa.Date(), nullable=True),
    sa.Column('test_duration', sa.String(length=50), nullable=True),
    sa.Column('related_proposals', sa.JSON(), nullable=True),
    sa.Column('synergy_check', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ecosystem_id'], ['ecosystems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_proposals_ecosystem_id', 'proposals', ['ecosystem_id'], unique=False)
    op.create_table('advice_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('proposal_id', sa.Uuid(), nullable=False),
    sa.Column('advice_window_start', sa.Date(), nullable=True),
    sa.Column('advice_window_end', sa.Date(), nullable=True),
    sa.Column('urgency', sa.String(length=50), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('proposer_modifications', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_advice_logs_proposal_id', 'advice_logs', ['proposal_id'], unique=False)
    op.create_table('agent_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ecosystem_id', sa.Uuid(), nullable=False),
    sa.Column('member_id', sa.Uuid(), nullable=True),
    sa.Column('skill_name', sa.String(length=100), nullable=True),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ecosystem_id'], ['ecosystems.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_sessions_ecosystem_id', 'agent_sessions', ['ecosystem_id'], unique=False)
    op.create_table('agreement_ratification_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agreement_id', sa.Uuid(), nullable=False),
    sa.Column('participant', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('position', sa.String(length=50), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agreement_id'], ['agreements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agreement_ratification_records_agreement_id', 'agreement_ratification_records', ['agreement_id'], unique=False)
    op.create_table('amendment_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ecosystem_id', sa.Uuid(), nullable=False),
    sa.Column('amendment_id', sa.String(length=100), nullable=False),
    sa.Column('parent_agreement_id', sa.Uuid(), nullable=False),
    sa.Column('parent_agreement_version', sa.String(length=20), nullable=True),
    sa.Column('amendment_type', sa.String(length=50), nullable=False),
    sa.Column('proposed_by', sa.String(length=255), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('changes', sa.JSON(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('act_level_used', sa.String(length=50), nullable=True),
    sa.Column('consent_record_id', sa.Uuid(), nullable=True),
    sa.Column('new_agreement_version', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ecosystem_id'], ['ecosystems.id'], ),
    sa.ForeignKeyConstraint(['parent_agreement_id'], ['agreements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_amendment_records_ecosystem_id', 'amendment_records', ['ecosystem_id'], unique=False)
    op.create_table('consent_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('proposal_id', sa.Uuid(), nullable=False),
    sa.Column('consent_mode', sa.String(length=50), nullable=False),
    sa.Column('weighting_model', sa.String(length=100), nullable=True),
    sa.Column('facilitator', sa.String(length=255), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('quorum_required', sa.String(length=50), nullable=True),
    sa.Column('quorum_met', sa.Boolean(), nullable=False),
    sa.Column('outcome', sa.String(length=100), nullable=True),
    sa.Column('escalation_level', sa.String(length=50), nullable=True),
    sa.Column('final_proposal_version', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_consent_records_proposal_id', 'consent_records', ['proposal_id'], unique=False)
    op.create_table('decision_dissent_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('decision_record_id', sa.Uuid(), nullable=False),
    sa.Column('objector', sa.String(length=255), nullable=False),
    sa.Column('objection', sa.Text(), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['decision_record_id'], ['decision_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_decision_dissent_records_decision_record_id', 'decision_dissent_records', ['decision_record_id'], unique=False)
    op.create_table('decision_participants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('decision_record_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('position', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['decision_record_id'], ['decision_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_decision_participants_decision_record_id', 'decision_participants', ['decision_record_id'], unique=False)
    op.create_table('decision_semantic_tags',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('decision_record_id', sa.Uuid(), nullable=False),
    sa.Column('topic', sa.JSON(), nullable=True),
    sa.Column('affected_parties', sa.JSON(), nullable=True),
    sa.Column('ecosystem_scope', sa.String(length=100), nullable=True),
    sa.Column('urgency_at_time', sa.String(length=50), nullable=True),
    sa.Column('related_precedents', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['decision_record_id'], ['decision_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_decision_semantic_tags_decision_record_id', 'decision_semantic_tags', ['decision_record_id'], unique=False)
    op.create_table('domains',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ecosystem_id', sa.Uuid(), nullable=False),
    sa.Column('domain_id', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('current_steward', sa.String(length=255), nullable=True),
    sa.Column('steward_id', sa.Uuid(), nullable=True),
    sa.Column('parent_domain_id', sa.Uuid(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('metric_definitions', sa.JSON(), nullable=True),
    sa.Column('elements', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ecosystem_id'], ['ecosystems.id'], ),
    sa.ForeignKeyConstraint(['parent_domain_id'], ['domains.id'], ),
    sa.ForeignKeyConstraint(['steward_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_domains_ecosystem_id', 'domains', ['ecosystem_id'], unique=False)
    op.create_table('member_onboarding',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('member_id', sa.Uuid(), nullable=False),
    sa.Column('facilitator', sa.String(length=255), nullable=True),
    sa.Column('mentor_id', sa.Uuid(), nullable=True),
    sa.Column('uaf_version_consented', sa.String(length=20), nullable=True),
    sa.Column('consent_date', sa.Date(), nullable=True),
    sa.Column('cooling_off_start', sa.Date(), nullable=True),
    sa.Column('cooling_off_end', sa.Date(), nullable=True),
    sa.Column('section_consents', sa.JSON(), nullable=True),
    sa.Column('checklist_items', sa.JSON(), nullable=True),
    sa.Column('completion_percentage', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['mentor_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_member_onboarding_member_id', 'member_onboarding', ['member_id'], unique=False)
    op.create_table('member_status_transitions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('member_id', sa.Uuid(), nullable=False),
    sa.Column('from_status', sa.String(length=50), nullable=False),
    sa.Column('to_status', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('trigger', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_member_status_transitions_member_id', 'member_status_transitions', ['member_id'], unique=False)
    op.create_table('review_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ecosystem_id', sa.Uuid(), nullable=False),
    sa.Column('review_id', sa.String(length=100), nullable=False),
    sa.Column('agreement_id', sa.Uuid(), nullable=False),
    sa.Column('agreement_version', sa.String(length=20), nullable=True),
    sa.Column('review_type', sa.String(length=50), nullable=False),
    sa.Column('trigger', sa.String(length=255), nullable=True),
    sa.Column('review_body', sa.JSON(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('evaluation', sa.JSON(), nullable=True),
    sa.Column('outcome', sa.String(length=100), nullable=True),
    sa.Column('next_review_date', sa.Date(), nullable=True),
    sa.Column('follow_up_actions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agreement_id'], ['agreements.id'], ),
    sa.ForeignKeyConstraint(['ecosystem_id'], ['ecosystems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_review_records_ecosystem_id', 'review_records', ['ecosystem_id'], unique=False)
    op.create_table('test_reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('proposal_id', sa.Uuid(), nullable=False),
    sa.Column('test_start_date', sa.Date(), nullable=True),
    sa.Column('test_end_date', sa.Date(), nullable=True),
    sa.Column('midpoint_checkin_date', sa.Date(), nullable=True),
    sa.Column('revert_procedure', sa.Text(), nullable=True),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('midpoint_findings', sa.Text(), nullable=True),
    sa.Column('outcome', sa.String(length=100), nullable=True),
    sa.Column('extension_end_date', sa.Date(), nullable=True),
    sa.Column('modifications', sa.Text(), nullable=True),
    sa.Column('next_action', sa.String(length=255), nullable=True),
    sa.Column('agreement_registry_id', sa.String(length=100), nullable=True),
    sa.Column('success_criteria_summary', sa.Text(), nullable=True),
    sa.Column('reviewer_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_test_reports_proposal_id', 'test_reports', ['proposal_id'], unique=False)
    op.create_table('advice_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('advice_log_id', sa.Uuid(), nullable=False),
    sa.Column('advisor', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('azpo', sa.String(length=100), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('advice_text', sa.Text(), nullable=True),
    sa.Column('proposer_response', sa.Text(), nullable=True),
    sa.Column('integration_status', sa.String(length=50), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['advice_log_id'], ['advice_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_advice_entries_advice_log_id', 'advice_entries', ['advice_log_id'], unique=False)
    op.create_table('advice_non_respondents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('advice_log_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('notified_date', sa.Date(), nullable=True),
    sa.Column('follow_up_sent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['advice_log_id'], ['advice_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_advice_non_respondents_advice_log_id', 'advice_non_respondents', ['advice_log_id'], unique=False)
    op.create_table('consent_integration_rounds',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('consent_record_id', sa.Uuid(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('modifications_made', sa.Text(), nullable=True),
    sa.Column('outcome', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['consent_record_id'], ['consent_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_consent_integration_rounds_consent_record_id', 'consent_integration_rounds', ['consent_record_id'], unique=False)
    op.create_table('consent_participants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('consent_record_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('azpo', sa.String(length=100), nullable=True),
    sa.Column('position', sa.String(length=50), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('round', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['consent_record_id'], ['consent_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_consent_participants_consent_record_id', 'consent_participants', ['consent_record_id'], unique=False)
    op.create_table('domain_elements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('domain_id', sa.Uuid(), nullable=False),
    sa.Column('element_name', sa.String(length=100), nullable=False),
    sa.Column('element_value', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_domain_elements_domain_id', 'domain_elements', ['domain_id'], unique=False)
    op.create_table('domain_metrics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('domain_id', sa.Uuid(), nullable=False),
    sa.Column('metric', sa.String(length=255), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=True),
    sa.Column('measurement_method', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_domain_metrics_domain_id', 'domain_metrics', ['domain_id'], unique=False)
    op.create_table('test_success_criteria',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('test_report_id', sa.Uuid(), nullable=False),
    sa.Column('criterion', sa.String(length=500), nullable=False),
    sa.Column('met', sa.Boolean(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['test_report_id'], ['test_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_test_success_criteria_test_report_id', 'test_success_criteria', ['test_report_id'], unique=False)
    op.create_table('consent_objections_addressed',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('integration_round_id', sa.Uuid(), nullable=False),
    sa.Column('objector', sa.String(length=255), nullable=False),
    sa.Column('objection', sa.Text(), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['integration_round_id'], ['consent_integration_rounds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_consent_objections_addressed_integration_round_id', 'consent_objections_addressed', ['integration_round_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_consent_objections_addressed_integration_round_id', table_name='consent_objections_addressed')
    op.drop_table('consent_objections_addressed')
    op.drop_index('ix_test_success_criteria_test_report_id', table_name='test_success_criteria')
    op.drop_table('test_success_criteria')
    op.drop_index('ix_domain_metrics_domain_id', table_name='domain_metrics')
    op.drop_table('domain_metrics')
    op.drop_index('ix_domain_elements_domain_id', table_name='domain_elements')
    op.drop_table('domain_elements')
    op.drop_index('ix_consent_participants_consent_record_id', table_name='consent_participants')
    op.drop_table('consent_participants')
    op.drop_index('ix_consent_integration_rounds_consent_record_id', table_name='consent_integration_rounds')
    op.drop_table('consent_integration_rounds')
    op.drop_index('ix_advice_non_respondents_advice_log_id', table_name='advice_non_respondents')
    op.drop_table('advice_non_respondents')
    op.drop_index('ix_advice_entries_advice_log_id', table_name='advice_entries')
    op.drop_table('advice_entries')
    op.drop_index('ix_test_reports_proposal_id', table_name='test_reports')
    op.drop_table('test_reports')
    op.drop_index('ix_review_records_ecosystem_id', table_name='review_records')
    op.drop_table('review_records')
    op.drop_index('ix_member_status_transitions_member_id', table_name='member_status_transitions')
    op.drop_table('member_status_transitions')
    op.drop_index('ix_member_onboarding_member_id', table_name='member_onboarding')
    op.drop_table('member_onboarding')
    op.drop_index('ix_domains_ecosystem_id', table_name='domains')
    op.drop_table('domains')
    op.drop_index('ix_decision_semantic_tags_decision_record_id', table_name='decision_semantic_tags')
    op.drop_table('decision_semantic_tags')
    op.drop_index('ix_decision_participants_decision_record_id', table_name='decision_participants')
    op.drop_table('decision_participants')
    op.drop_index('ix_decision_dissent_records_decision_record_id', table_name='decision_dissent_records')
    op.drop_table('decision_dissent_records')
    op.drop_index('ix_consent_records_proposal_id', table_name='consent_records')
    op.drop_table('consent_records')
    op.drop_index('ix_amendment_records_ecosystem_id', table_name='amendment_records')
    op.drop_table('amendment_records')
    op.drop_index('ix_agreement_ratification_records_agreement_id', table_name='agreement_ratification_records')
    op.drop_table('agreement_ratification_records')
    op.drop_index('ix_agent_sessions_ecosystem_id', table_name='agent_sessions')
    op.drop_table('agent_sessions')
    op.drop_index('ix_advice_logs_proposal_id', table_name='advice_logs')
    op.drop_table('advice_logs')
    op.drop_index('ix_proposals_ecosystem_id', table_name='proposals')
    op.drop_table('proposals')
    op.drop_index('ix_members_ecosystem_id', table_name='members')
    op.drop_table('members')
    op.drop_index('ix_decision_records_ecosystem_id', table_name='decision_records')
    op.drop_table('decision_records')
    op.drop_index('ix_agreements_ecosystem_id', table_name='agreements')
    op.drop_table('agreements')
    op.drop_table('ecosystems')
    # ### end Alembic commands ###
