[build]
builder = "DOCKERFILE"
dockerfilePath = "agent/Dockerfile"
watchPatterns = ["agent/**", "neos-core/**"]

[deploy]
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
